apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
<<<<<<< HEAD
      storage: 500Mi
=======
      storage: 750Mi
>>>>>>> change-deploy
status: {}
