apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 666Mi
status: {}
