apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.service.healthcheck.readiness.interval: 10s
    kompose.service.healthcheck.readiness.retries: "3"
    kompose.service.healthcheck.readiness.start_period: 30s
    kompose.service.healthcheck.readiness.test: CMD curl -f "http://localhost:80"
    kompose.service.healthcheck.readiness.timeout: 10s
    kompose.service.type: nodeport
    kompose.version: 1.26.0 (40646f47)
    kompose.volume.size: 750Mi
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: proxy
  type: NodePort
status:
  loadBalancer: {}
